# Generated by Django 4.2.7 on 2025-10-15 16:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name or company name of the client', max_length=200, verbose_name='Name/Company Name')),
                ('email', models.EmailField(help_text='Primary contact email', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be between 9 and 15 digits.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, help_text='Complete address', verbose_name='Address')),
                ('city', models.CharField(blank=True, default='Madrid', max_length=100, verbose_name='City')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Postal Code')),
                ('province', models.CharField(blank=True, default='Madrid', max_length=50, verbose_name='Province')),
                ('client_type', models.CharField(choices=[('individual', '🧑 Individual'), ('professional', '👨\u200d💼 Professional'), ('company', '🏢 Company'), ('architect', '📐 Architect'), ('installer', '🔧 Installer'), ('distributor', '📦 Distributor')], default='individual', help_text='Select the client type', max_length=20, verbose_name='Client Type')),
                ('tax_id', models.CharField(blank=True, help_text='Tax identification number', max_length=20, verbose_name='Tax ID/CIF/NIF')),
                ('company_name', models.CharField(blank=True, help_text='Official company name (if different)', max_length=200, verbose_name='Company Name')),
                ('business_activity', models.CharField(blank=True, help_text='Main business activity', max_length=100, verbose_name='Business Activity')),
                ('preferred_products', models.TextField(blank=True, help_text='Sanitary products the client is interested in', verbose_name='Products of Interest')),
                ('notes', models.TextField(blank=True, help_text='Additional information about the client', verbose_name='Internal Notes')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the client is active', verbose_name='Active')),
                ('is_vip', models.BooleanField(default=False, help_text='Client with preferential treatment', verbose_name='VIP Client')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, help_text='Credit limit assigned to the client', max_digits=10, verbose_name='Credit Limit')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('last_purchase_date', models.DateTimeField(blank=True, null=True, verbose_name='Last Purchase Date')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('frequent', '🔄 Frequent Client'), ('wholesale', '📦 Wholesaler'), ('retail', '🏪 Retailer'), ('contractor', '🔨 Contractor'), ('architect', '📐 Architecture Firm'), ('vip', '⭐ VIP Client'), ('new', '🆕 New Client'), ('inactive', '💤 Inactive Client')], max_length=50, unique=True, verbose_name='Segment Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Applicable discount percentage', max_digits=5, verbose_name='Discount %')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Segment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clients', models.ManyToManyField(blank=True, related_name='segments', to='clients.client', verbose_name='Clients')),
            ],
            options={
                'verbose_name': 'Client Segment',
                'verbose_name_plural': 'Client Segments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Contact Name')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Position/Title')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Email')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='Contact Phone')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Department')),
                ('is_main_contact', models.BooleanField(default=False, verbose_name='Main Contact')),
                ('can_authorize_orders', models.BooleanField(default=False, verbose_name='Can Authorize Orders')),
                ('notes', models.TextField(blank=True, verbose_name='Contact Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Client Contact',
                'verbose_name_plural': 'Client Contacts',
                'ordering': ['client', '-is_main_contact', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['name'], name='clients_cli_name_5ab7bc_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email'], name='clients_cli_email_56b9fc_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_type'], name='clients_cli_client__1e0f73_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_active'], name='clients_cli_is_acti_57c1e7_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['created_at'], name='clients_cli_created_4ff9ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_client_email'),
        ),
        migrations.AlterUniqueTogether(
            name='clientcontact',
            unique_together={('client', 'email')},
        ),
    ]
